ACCOUNTS = [ "GDSZLI63D66PYUARJPCFNGXVTXAVHLWJP35KFNJ2UJP2CVQLP52LMKBI", ]
VERSION = "0.1.0"
SIGNING_KEY = "SAJRKZFHZXWL3SX3E332RGLRWT3HNTW3P6P757PAU7HULRNVMJBWCP5K"
NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"

TRANSFER_SERVER = "https://testanchor.stellar.org/sep6"
TRANSFER_SERVER_SEP0024 = "https://testanchor.stellar.org/sep24"
WEB_AUTH_ENDPOINT = "https://testanchor.stellar.org/auth"
KYC_SERVER = "https://testanchor.stellar.org/kyc"
DIRECT_PAYMENT_SERVER = "https://testanchor.stellar.org/sep31"

[[CURRENCIES]]
code = "SRT"
issuer = "GCDNJUBQSX7AJWLJACMJ7I4BC3Z47BQUTMHEICZLE6MU4KQBRYG5JY6B"
status = "test"
is_asset_anchored = false
anchor_asset_type = "other"
desc = "A fake anchored asset to use with this example anchor server."

[[CURRENCIES]]
code = "MULT"
issuer = "GDLD3SOLYJTBEAK5IU4LDS44UMBND262IXPJB3LDHXOZ3S2QQRD5FSMM"
status = "test"
is_asset_anchored = false
anchor_asset_type = "other"
desc = "A fake anchored asset that has a multsig distribution account as an example."

[[PRINCIPALS]]
name = "Jacob Urban"
email = "jake@stellar.org"
keybase = "jakeurban"
github = "https://www.github.com/JakeUrban"

[DOCUMENTATION]
ORG_NAME = "Stellar Development Foundation"
ORG_URL = "https://stellar.org"
ORG_DESCRIPTION = "SEP 24 reference server."
ORG_KEYBASE = "stellar.public"
ORG_TWITTER = "StellarOrg"
ORG_GITHUB = "stellar"
